[account]
Token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyXzg4YzViODcyNzQ5OTRiZTAwMzMzNWUwMDIwNmJmMjhiIiwiaWF0IjoxNzczODAyNTQ4LCJleHAiOjE3NzQ0MDczNDh9.-kZcgdYJoyr4fhNE0TIsNJKw7mmN2vYtn0Js2Lovq2_8GWotvdt83M8G48nLs3Z6BnrQKJeqyn5erFOTiblulg

[settings]
# 筛选多少天内的活动
days_ahead = 3